#!/bin/sh

(cd $HOME ; [ ! -d env ] && virtualenv env)

. $HOME/env/bin/activate

python createdb.py
python manage.py syncdb --noinput 
#django-admin.py migrate --noinput 
python mkadmin.py
mkdir -p /home/dotcloud/data/media /home/dotcloud/volatile/static
python manage.py collectstatic --noinput
